import zipfile, re, shutil, os, pandas as pd

src = r'C:\Users\ks2479\Documents\GitHub\oov-virtual-museum02\oov_data_new.xlsx'
repair_copy = src + '.bak'
fixed = src + '.fixed.xlsx'

shutil.copy(src, repair_copy)
with zipfile.ZipFile(repair_copy, 'r') as zin:
    with zipfile.ZipFile(fixed, 'w', compression=zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename.startswith('xl/worksheets/sheet'):
                text = data.decode('utf-8')
                data = re.sub(r'<v>NaN</v>', '', text).encode('utf-8')
            zout.writestr(item, data)

df = pd.read_excel(fixed, dtype=str)

COLS = ['itemID', 'filename', 'path', 'title', 'description', 'type', 'keywords',
        'subjectCountry', 'issuingCountry', 'creator', 'issueDate', 'currency',
        'language', 'numberPages', 'period', 'notes']

rows_data = [
    {
        'filename': 'goetzmann0936.jpg',
        'itemID': '936',
        'path': '/images/goetzmann0936.jpg',
        'title': "Chambre Imperiale et Royale d'Assurance d'Anvers, Marine Insurance Policy, 1811",
        'description': "Marine insurance policy issued by the Chambre Imperiale et Royale d'Assurance d'Anvers (Antwerp Imperial and Royal Insurance Chamber). Headed 'AU NOM DE DIEU.' Insures cargo belonging to M. Daniele Borges, merchant of Holland, for a voyage destined for Paris/Constantinople/Brussels. Handwritten details of insured party, goods, amount, and route. Dated 18 April 1811. Signed by officers of the Chamber with wax seals.",
        'type': 'insurance policy',
        'keywords': 'marine insurance, Antwerp, Napoleon era, cargo, Belgium',
        'subjectCountry': 'Belgium',
        'issuingCountry': 'Belgium',
        'creator': "Chambre Imperiale et Royale d'Assurance d'Anvers",
        'issueDate': '1811-04-18',
        'currency': '',
        'language': 'French',
        'numberPages': '1',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0937.jpg',
        'itemID': '937',
        'path': '/images/goetzmann0937.jpg',
        'title': "Contract van Overleeving 'De Tyd Baard Roozen,' Letter G - Subscriber List (p.1 of 4)",
        'description': "First page of a 4-page Dutch survival lottery/tontine contract titled 'Contract van Overleeving Letter G, onder de Zinspreuke De Tyd Baard Roozen' (Contract of Survival, Motto: Time Bears Roses). Marked 'Copia.' Lists tontine subscribers numbered from approximately 30 onward, with names including Johanna Freriks, Carolina Elfens, and others. Printed conditions (Conditien en Voorwaarden) follow in Article form. Amsterdam, 1779.",
        'type': 'tontine',
        'keywords': 'tontine, Netherlands, survival lottery, annuity, Amsterdam, subscribers, De Tyd Baard Roozen',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': '',
        'issueDate': '1779',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '4',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0938.jpg',
        'itemID': '938',
        'path': '/images/goetzmann0938.jpg',
        'title': "Contract van Overleeving 'De Tyd Baard Roozen' - Conditions Part 1 (p.2 of 4)",
        'description': "Second page of the 4-page 'De Tyd Baard Roozen' Dutch tontine contract (Contract van Overleeving Letter G). Contains printed conditions (Conditien en Voorwaarden), numbered articles detailing rules of the tontine including interest payments, management, and rights of subscribers. Amsterdam, 1779.",
        'type': 'tontine',
        'keywords': 'tontine, Netherlands, survival lottery, annuity, Amsterdam, conditions',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': '',
        'issueDate': '1779',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '4',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0939.jpg',
        'itemID': '939',
        'path': '/images/goetzmann0939.jpg',
        'title': "Contract van Overleeving 'De Tyd Baard Roozen' - Conditions Part 2, Signed (p.3 of 4)",
        'description': "Third page of the 4-page 'De Tyd Baard Roozen' Dutch tontine contract. Contains concluding articles and conditions. Signed 'Actum Amsterdam, den 3 September 1779' by directors including Hendrik Laschenberg and Hendrik Roeldam.",
        'type': 'tontine',
        'keywords': 'tontine, Netherlands, survival lottery, annuity, Amsterdam, 1779, Laschenberg',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': 'Hendrik Laschenberg, Hendrik Roeldam',
        'issueDate': '1779-09-03',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '4',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0940.jpg',
        'itemID': '940',
        'path': '/images/goetzmann0940.jpg',
        'title': "Contract van Overleeving 'De Tyd Baard Roozen' - Individual Certificate, Petronella Fox (p.4 of 4)",
        'description': "Fourth page of the 'De Tyd Baard Roozen' tontine: individual subscription certificate issued to Juffr. Petronella Fox, inscribed on the Kleine Lyft, contribution of f.10-. Certified by the directors and administrator. Dated 'Actum Amsterdam, den 31 October 1774.' Lower half contains handwritten rows of annual payment/dividend records.",
        'type': 'tontine',
        'keywords': 'tontine, Netherlands, certificate, annuity, Petronella Fox, Amsterdam, 1774, payment records',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': 'Directeuren en Administrateur, Amsterdam',
        'issueDate': '1774-10-31',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '4',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0941.jpg',
        'itemID': '941',
        'path': '/images/goetzmann0941.jpg',
        'title': "French Consular Certificate of Egyptian Financial Document, Alexandria, 1866",
        'description': "Handwritten French administrative certificate from Alexandria, Egypt. Bears official seals of the French consulate. References a financial document number (numero 932) and a monetary sum. Certified 'conforme' and legalized for signature by the French Consul General in Alexandria, 17 June 1866. Likely a transfer or certification document for Egyptian government debt bonds.",
        'type': 'certificate',
        'keywords': 'Egypt, French consulate, Alexandria, bond transfer, certification, Egyptian debt, 1866',
        'subjectCountry': 'Egypt',
        'issuingCountry': 'Egypt',
        'creator': 'French Consulate General, Alexandria',
        'issueDate': '1866-06-17',
        'currency': '',
        'language': 'French',
        'numberPages': '1',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0942.jpg',
        'itemID': '942',
        'path': '/images/goetzmann0942.jpg',
        'title': "Ottoman/Egyptian Financial Document with French-Austrian Consular Certifications, 1866",
        'description': "Bilingual Arabic-French document from Egypt, 1866. Main text in Arabic/Ottoman script; French annotations reference Florence (4 November 1866) and a sum of 2,000. Bears official seals of the Egyptian Ministry of Finance (Mehmed Hafiz Pasha, 15 May 1866) and the Austrian Consul in Florence (15 July 1866). Likely a financial certificate or bond transfer document for Egyptian government debt, notarized through the Austrian consulate in Florence.",
        'type': 'certificate',
        'keywords': 'Egypt, Ottoman, Arabic, Florence, Austrian consulate, bond transfer, Egyptian debt, 1866',
        'subjectCountry': 'Egypt',
        'issuingCountry': 'Egypt',
        'creator': 'Egyptian Ministry of Finance',
        'issueDate': '1866-05-15',
        'currency': '',
        'language': 'Arabic, French',
        'numberPages': '1',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0943.jpg',
        'itemID': '943',
        'path': '/images/goetzmann0943.jpg',
        'title': "Dutch Negotiation Contract, Abraham van Berk & Vollemioven - Subscriber List, 1787 (p.1 of 3)",
        'description': "First page of a 3-page Dutch negotiation/annuity share document, commencing 'Heden den Eerste May des Jaars Seventeen Honderd Seven-en-Tachtig' (1 May 1787). Directed by Abraham van Berk and Hendrik Vollemioven with 10 directors total. Lists numbered female shareholders with names including Johanna Freriks, Carolina Elfens, Carolina Belfleur, and others. Printed conditions follow. Amsterdam, 1787.",
        'type': 'share',
        'keywords': 'Netherlands, negotiation, annuity, Amsterdam, 1787, Abraham van Berk, subscribers, female shareholders',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': 'Abraham van Berk, Hendrik Vollemioven',
        'issueDate': '1787-05-01',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '3',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0944.jpg',
        'itemID': '944',
        'path': '/images/goetzmann0944.jpg',
        'title': "Dutch Negotiation Contract, Abraham van Berk & Vollemioven - Conditions (p.2 of 3)",
        'description': "Second page of the 3-page Dutch negotiation/annuity share document by Abraham van Berk and Hendrik Vollemioven, Amsterdam 1787. Contains printed conditions and articles governing the negotiation, including payment terms, interest obligations, and rights and duties of directors and participants.",
        'type': 'share',
        'keywords': 'Netherlands, negotiation, annuity, Amsterdam, 1787, conditions',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': 'Abraham van Berk, Hendrik Vollemioven',
        'issueDate': '1787',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '3',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0945.jpg',
        'itemID': '945',
        'path': '/images/goetzmann0945.jpg',
        'title': "Dutch Negotiation Contract, Abraham van Berk & Vollemioven - Receipt for 1,000 Guilders (p.3 of 3)",
        'description': "Third and final page of the Dutch negotiation share document by Abraham van Berk and Hendrik Vollemioven. Concluding conditions and a printed receipt for 'EEN DUIZEND GULDENS' (one thousand guilders) for one share in the negotiation, payable on 1 November and 1 May. Receipt No. 507. Dated Amsterdam, 3 May 1787.",
        'type': 'share',
        'keywords': 'Netherlands, negotiation, annuity, Amsterdam, 1787, receipt, 1000 guilders',
        'subjectCountry': 'Netherlands',
        'issuingCountry': 'Netherlands',
        'creator': 'Abraham van Berk, Hendrik Vollemioven',
        'issueDate': '1787-05-03',
        'currency': 'Dutch guilder',
        'language': 'Dutch',
        'numberPages': '3',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0946.jpg',
        'itemID': '946',
        'path': '/images/goetzmann0946.jpg',
        'title': "Rancocus Toll-Bridge, One Share No. 29, Abel James, 1793",
        'description': "Share certificate No. 29 for one share in the stock of the President, Managers, & Company of Rancocus Toll-Bridge. Issued to Abel James on the eighteenth day of February 1793. Signed by Joshua M. Wallace as President and William [?] juno as Treasurer. The Rancocas Creek Toll-Bridge was located in Burlington County, New Jersey.",
        'type': 'share',
        'keywords': 'toll bridge, New Jersey, Rancocas, Abel James, 1793, infrastructure, early America',
        'subjectCountry': 'United States',
        'issuingCountry': 'United States',
        'creator': 'President, Managers, & Company of Rancocus Toll-Bridge',
        'issueDate': '1793-02-18',
        'currency': '',
        'language': 'English',
        'numberPages': '1',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0947.jpg',
        'itemID': '947',
        'path': '/images/goetzmann0947.jpg',
        'title': "Imperial Chinese Government 5% Tientsin-Pukow Railway Loan, 100 Pound Bond No. 24305, 1908",
        'description': "Bearer bond for 100 pounds sterling from the Imperial Chinese Government 5% Tientsin-Pukow Railway Loan of 5,000,000 pounds sterling. Bond No. 24305. Printed in orange and black with decorative border. Bears two Chinese calligraphic red seals and one purple seal. Countersigned by the Chinese Central Railway, London. Issued London, 1st September 1908. The Tientsin-Pukow (Tianjin-Pukou) Railway was a major north-south Chinese rail line financed through British loans.",
        'type': 'bond',
        'keywords': 'China, railway, Tientsin-Pukow, imperial, sterling, London, 1908, infrastructure, Chinese government',
        'subjectCountry': 'China',
        'issuingCountry': 'China',
        'creator': 'Imperial Chinese Government / Chinese Central Railway',
        'issueDate': '1908-09-01',
        'currency': 'British pound sterling',
        'language': 'English, Chinese',
        'numberPages': '2',
        'period': '20th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0948.jpg',
        'itemID': '948',
        'path': '/images/goetzmann0948.jpg',
        'title': "Imperial Chinese Government 5% Tientsin-Pukow Railway Loan, 100 Pound Bond No. 24305 - Interior Pages (p.2 of 2)",
        'description': "Interior spread of the Imperial Chinese Government Tientsin-Pukow Railway 5% 100-pound bond No. 24305. Left panel shows the redemption/amortization table for the full 5,000,000 pound loan; right panel contains full printed text of the bond conditions including interest payment terms, redemption schedule, and trustee details.",
        'type': 'bond',
        'keywords': 'China, railway, Tientsin-Pukow, imperial, sterling, amortization table, conditions, 1908',
        'subjectCountry': 'China',
        'issuingCountry': 'China',
        'creator': 'Imperial Chinese Government / Chinese Central Railway',
        'issueDate': '1908-09-01',
        'currency': 'British pound sterling',
        'language': 'English, Chinese',
        'numberPages': '2',
        'period': '20th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0949.jpg',
        'itemID': '949',
        'path': '/images/goetzmann0949.jpg',
        'title': "Kousanie Tea Company, Limited, Share Certificate No. 1647, W. Campbell & Co., 1874",
        'description': "Share certificate No. 1647 for one share in the Kousanie Tea Company, Limited, registered under Act XIX of 1857 of the Legislative Council of India. Capital: Rs 3,45,000 divided into 3,450 shares of Rs 100 each. Holder: W. Campbell & Co. Cl. Dated Kousanie, 22nd April 1874. Signed by Manager and Managing Director. Bears a purple one-anna Indian revenue stamp.",
        'type': 'share',
        'keywords': 'tea company, India, British India, plantation, Kousanie, 1874, revenue stamp',
        'subjectCountry': 'India',
        'issuingCountry': 'India',
        'creator': 'Kousanie Tea Company, Limited',
        'issueDate': '1874-04-22',
        'currency': 'Indian rupee',
        'language': 'English',
        'numberPages': '2',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0950.jpg',
        'itemID': '950',
        'path': '/images/goetzmann0950.jpg',
        'title': "Kousanie Tea Company, Limited, Share No. 1647 - Transfer Records (p.2 of 2)",
        'description': "Reverse of Kousanie Tea Company share certificate No. 1647. Contains transfer register records. Transfer Register No. 113, dated 23rd April (year illegible), signed by Manager. Notes transfers of the share, ultimately to the Reverend Henry Francis Martin and the Venerable William Lpeek [?], Archdeacon of Kilmoe.",
        'type': 'share',
        'keywords': 'tea company, India, British India, transfer, Kousanie, Archdeacon of Kilmoe, reverse',
        'subjectCountry': 'India',
        'issuingCountry': 'India',
        'creator': 'Kousanie Tea Company, Limited',
        'issueDate': '1874-04-22',
        'currency': 'Indian rupee',
        'language': 'English',
        'numberPages': '2',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0951.jpg',
        'itemID': '951',
        'path': '/images/goetzmann0951.jpg',
        'title': "Insurance Company of the State of Pennsylvania, Share Transfer, Lawler to du Ponceau, 1795",
        'description': "Share transfer certificate in which Matthew Lawler assigns and transfers shares in the Capital or Joint Stock of the Insurance Company of the State of Pennsylvania to Peter Stephen du Ponceau. Dated the twenty-ninth day of August 1795 (year partially illegible, likely 1795 or 1796). Witnessed by John Lewis. Signed by Mat. Lawler.",
        'type': 'share transfer',
        'keywords': 'insurance, Pennsylvania, Philadelphia, share transfer, Matthew Lawler, du Ponceau, 1795',
        'subjectCountry': 'United States',
        'issuingCountry': 'United States',
        'creator': 'Matthew Lawler',
        'issueDate': '1795-08-29',
        'currency': '',
        'language': 'English',
        'numberPages': '1',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0952.jpg',
        'itemID': '952',
        'path': '/images/goetzmann0952.jpg',
        'title': "Liverpool Colquitt Street Tontine, Share No. 29, Frances Harmand Hanly, 1807",
        'description': "Tontine share certificate No. 29 for the Liverpool Colquitt Street Tontine, certifying that Frances Harmand Hanly and Richard Stewart Hanly, children of Richard Hanly, are proprietors of Share No. 29. Nominee: Frances Harmand Hanly, daughter of Richard Hanly of Liverpool, Banker. By transfer from Richard Hanly (3 shares). Dated Liverpool, 7 October 1807. Entered by Charles Bird. Printed by J. Gore.",
        'type': 'tontine',
        'keywords': 'tontine, Liverpool, Colquitt Street, Hanly, 1807, property, England',
        'subjectCountry': 'United Kingdom',
        'issuingCountry': 'United Kingdom',
        'creator': 'Liverpool Colquitt Street Tontine',
        'issueDate': '1807-10-07',
        'currency': 'British pound sterling',
        'language': 'English',
        'numberPages': '1',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0953.jpg',
        'itemID': '953',
        'path': '/images/goetzmann0953.jpg',
        'title': "Compagnie du Pont de la Mulatiere, Lyon - 500 Livres Action, No. 106",
        'description': "Share certificate (action) No. 106 for 500 livres invested in the Compagnie des Associes aux travaux du Pont de la Mulatiere, Lyon, France. The action produces 30 livres annual interest and a 100-livres premium upon redemption. Secured by special mortgage on toll revenues of the bridge and general mortgage on company assets. Signed at Lyon by company officers including Chard de [?], George [?], Sartore, and others. Dated ca. 1780s.",
        'type': 'share',
        'keywords': 'bridge, Lyon, France, infrastructure, Mulatiere, 500 livres, 18th century, toll bridge',
        'subjectCountry': 'France',
        'issuingCountry': 'France',
        'creator': 'Compagnie des Associes aux travaux du Pont de la Mulatiere',
        'issueDate': '1780s',
        'currency': 'French livre',
        'language': 'French',
        'numberPages': '1',
        'period': '18th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0954.jpg',
        'itemID': '954',
        'path': '/images/goetzmann0954.jpg',
        'title': "State of Mississippi / Mississippi Union Bank, $2,000 Five Per Cent Bond, with Coupon Sheet",
        'description': "Bearer bond for $2,000 issued by the State of Mississippi acknowledging debt to the Mississippi Union Bank, bearing interest at 5% per annum. Printed in black and white with an engraved vignette of a steamboat on a river. Full coupon sheet attached (approximately 24 coupons, each signed). Yellow adhesive label affixed. The Mississippi Union Bank operated in the late 1830s-1840s. Antebellum southern state banking bond.",
        'type': 'bond',
        'keywords': 'Mississippi, United States, bank, state bond, antebellum, coupon, Mississippi Union Bank, steamboat',
        'subjectCountry': 'United States',
        'issuingCountry': 'United States',
        'creator': 'State of Mississippi / Mississippi Union Bank',
        'issueDate': '1840s',
        'currency': 'US dollar',
        'language': 'English',
        'numberPages': '2',
        'period': '19th century',
        'notes': '',
    },
    {
        'filename': 'goetzmann0955.jpg',
        'itemID': '955',
        'path': '/images/goetzmann0955.jpg',
        'title': "State of Mississippi / Mississippi Union Bank Bond - Reverse: Transfer to London, 450 Pounds No. 372 (p.2 of 2)",
        'description': "Reverse of the Mississippi Union Bank $2,000 bond. The President and Directors of the Mississippi Union Bank designate the Bank of the United States in London as payment agent and assign the bond for value received. Signed by Steven Cass (Cashier) and H. S. Runnels (President). Overprinted in red: 'Mississippi State Bond. No. 372. 450 pounds. Redeemable Feb. 5th, 1850.' Lower coupon sheet shows individual coupons for 'Eleven Pounds five shillings sterling, payable at agency Bank United States, London.'",
        'type': 'bond',
        'keywords': 'Mississippi, United States, bank, state bond, London, sterling, coupon, Mississippi Union Bank, Runnels',
        'subjectCountry': 'United States',
        'issuingCountry': 'United States',
        'creator': 'State of Mississippi / Mississippi Union Bank',
        'issueDate': '1840s',
        'currency': 'British pound sterling',
        'language': 'English',
        'numberPages': '2',
        'period': '19th century',
        'notes': '',
    },
]

filled = 0
for row in rows_data:
    fn = row['filename']
    mask = df['filename'] == fn
    if not mask.any():
        print(f"WARNING: {fn} not found")
        continue
    for col in COLS:
        if col in row:
            df.loc[mask, col] = row[col]
    filled += 1

print(f"Filled {filled} rows.")
df.to_excel(fixed, index=False)
shutil.copy(fixed, src)
os.remove(fixed)
print(f"Saved -> {src}")
