const xlsx = require('../node_modules/xlsx');
const path = 'C:/Users/ks2479/Documents/GitHub/oov-virtual-museum02/oov_data_new.xlsx';

const wb = xlsx.readFile(path);
const ws = wb.Sheets['Documents'];
const data = xlsx.utils.sheet_to_json(ws, { header: 1 });

const headers = data[0];
const col = {};
headers.forEach((h, i) => { col[h] = i; });

function set(rowIdx, field, value) {
  if (col[field] === undefined) return;
  data[rowIdx][col[field]] = value;
}

const bubbleBase = {
  type: 'Illustration',
  subjectCountry: 'Great Britain',
  issuingCountry: 'Great Britain',
  creator: 'Anonymous',
  issueDate: '1720-01-01',
  language: 'English',
  numberPages: 1,
  period: '18th Century or before',
  notes: 'From the South Sea Bubble Playing Card deck, ca. 1720 (England)',
};

const cards = [
  { row: 55,
    title: 'Erecting Houses of Office in North Britain for Strangers and Travellers (South Sea Bubble Playing Card, Six of Hearts)',
    desc: 'A playing card depicting a scheme to erect public lavatories throughout northern Britain for strangers and travelers, showing a rural road with several small structures dotting the landscape, a man at the entrance of one building, a galloping horse in the background, and a boatman on a river in the foreground. The verse reads: "A usefull Project merrily advanc\'d, / tho\' chiefly by Tom-turdmen countenanced, / Design\'d to Sweeten the North British Nation, / And put Close Stools, and Bed Pans, out of fashion." The card satirizes a sanitation improvement scheme for Scotland, framing a potentially useful civic project as an absurd speculative venture promoted by cesspool workers ("Tom-turdmen"). The six of hearts pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The scatological humor, characteristic of this satirical series, underscores the satirist\'s view that bubble promoters were packaging the most basic human needs as profitable investment opportunities.' },

  { row: 56,
    title: 'Building Ships to let to Freight (South Sea Bubble Playing Card, Seven of Hearts)',
    desc: 'A playing card depicting a ship-building and freight charter scheme, showing a harbor scene with a large vessel in dry dock or being refitted while merchants and workers conduct business on the quayside beside scattered barrels and cargo. The verse reads: "Who but a Nest of Block-heads to their cost, / Would build new Ships for Freight, when Trade is lost; / To raise fresh Barks, must Surely be amusing, / When Hundreds rot in Docks for want of using." The card mocks a scheme to build new ships for the freight trade at a time when existing vessels lay idle in British ports due to depressed trading conditions. The seven of hearts pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse\'s accusation that the promoters are "Block-heads" building ships when hundreds already rot unused captures the satirist\'s view that bubble schemes were not merely fraudulent but actively irrational.' },

  { row: 57,
    title: 'Drying Malt by the Air (South Sea Bubble Playing Card, Eight of Hearts)',
    desc: 'A playing card depicting a scheme for drying malt using air rather than fire or heat, showing a malthouse building in a rainstorm with a figure leaning out of an upper window extending a rod into the downpour, wryly illustrating the absurdity of air-drying grain in the British climate. The verse reads: "Of all the Windy Projects now in vogue, / To fleece the Fool, and feed the cunning Rogue, / The Malting Bubble, seems to be most fair, / Because our Malt\'sters—own they work by Air." The eight of hearts pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The image of a figure catching rain ironically illustrates the impracticality of the proposed method. The verse\'s pun on "Windy Projects"—both figuratively empty and literally reliant on air—exemplifies the layered wordplay characteristic of this satirical card series.' },

  { row: 58,
    title: 'English Copper and Brass (South Sea Bubble Playing Card, Nine of Hearts)',
    desc: 'A playing card depicting an English copper and brass manufacturing scheme, showing a foundry interior with a worker pouring molten metal from a crucible before a blazing furnace while another operates bellows in the background, with a legal document labeled "Saire Facias" (Scire Facias) lying discarded on the floor. The verse reads: "The Headlong Fool that wants to be a Swopper, / Of Gold and Silver Coin, for English Copper, / May in Change Alley, prove himself an Ass, / And give Rich Mettle, for Adultrate Brass." The discarded writ of Scire Facias alludes to the legal proceedings used to dissolve fraudulent companies during the period of the Bubble Act, adding a topical legal dimension to the satirical scene. The nine of hearts pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The metallurgical metaphors contrasting gold and silver with adulterate brass serve as a sustained commentary on the exchange of genuine wealth for worthless speculative paper.' },

  { row: 59,
    title: 'Exporting Timber from Germany (South Sea Bubble Playing Card, Ten of Hearts)',
    desc: 'A playing card depicting a scheme to import and export timber from Germany, showing a busy harbor scene with a large sailing ship at anchor while workers slide logs down a timber run and merchants examine cargo on the quayside. The verse reads: "You that are Rich, and hasty to be Poor, / Buy Timber Export from the German Shoar; / For Gallowses, built up of Forreign Wood, / If rightly us\'d, may do Change Alley good." The ten of hearts pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. German timber was a genuine commodity of commercial importance for British shipbuilding, and the card satirizes the promotion of timber trading as a speculative investment vehicle. The verse\'s darkly comic suggestion that the imported wood would be best used for gallows to hang the swindlers of Change Alley encapsulates the satirist\'s contempt for bubble promoters.' },

  { row: 60,
    title: 'Sir John Law\'s Improvement of Land (South Sea Bubble Playing Card, Ace of Diamonds)',
    desc: 'A playing card satirizing a land improvement scheme attributed to Sir John Law, the Scottish economist whose Mississippi System in France had ignited the European speculative bubble of 1720, depicting women laboring in a garden or field while two men in the background hold a banner reading "An Act against Bubbles." The verse reads: "The Famous Knight that is the Sole Projector / Of this New Bubble, is a South Director, / But \'twould be better taken at his Hands, / To raise Poor South Sea than Improve Poor Lands." This card is notable for its direct reference to John Law and to the South Sea Company directorship, situating the land improvement scheme within the interconnected European financial crises of 1720. The banner referencing the Bubble Act—passed by the British Parliament in June 1720 to curb fraudulent company promotions—adds a contemporary legislative dimension to the satirical scene. The ace of diamonds pip in the upper left identifies this card\'s position in the South Sea Bubble playing card deck.' },

  { row: 61,
    title: 'Greenland Trade (South Sea Bubble Playing Card, Two of Diamonds)',
    desc: 'A playing card depicting the Greenland trade scheme, showing a coastal Arctic scene in which workers render a beached whale carcass over a large cauldron while a rowing boat and sailing ship are visible in the icy background. The verse reads: "This Project was to Catch to Cut and Boil / Huge Whales, and other Monstrous Fish to Oil, / A Stinking Bubble, tho\' of late so Dear, / Yet now the Greatest Sharers Stunk, for Fear." The two of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The Greenland whale fishery was a genuine and profitable industry that several bubble-era promoters attempted to exploit as a speculative vehicle, appealing to investors with the proven commercial value of whale oil and blubber. The verse\'s double meaning of "Stinking"—both the literal odor of whale rendering and the metaphorical failure of the investment scheme—is characteristic of the sardonic wordplay throughout this satirical card series.' },

  { row: 62,
    title: 'Insurance on Horses (South Sea Bubble Playing Card, Three of Diamonds)',
    desc: 'A playing card satirizing a horse insurance scheme, showing a rural scene in which a horse has thrown its rider and lies on the ground while other men look on and a second horse stands nearby, capturing the precise moment of equine accident that the insurance scheme purported to cover. The verse reads: "You that keep Horses to preserve your Ease, / And Pads to please your Wives, and Mistresses; / Insure their Lives, and if they Die we\'ll make / Full Satisfaction, or be bound to Break." The three of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse\'s final promise—"Full Satisfaction, or be bound to Break"—is a sardonic double entendre, simultaneously pledging compensation to policyholders and predicting the inevitable financial collapse of the insuring company. The image literalizes the risks the scheme promised to cover while satirizing the impracticality of its underlying business model.' },

  { row: 63,
    title: 'Bahama Islands (South Sea Bubble Playing Card, Five of Diamonds)',
    desc: 'A playing card depicting a scheme to settle and develop the Bahama Islands as a colonial investment, showing a crowd of prospective settlers boarding a ship at a dock while indigenous figures with bows and a chaotic landing scene are visible in the background, conveying the dangers awaiting emigrants. The verse reads: "Rare Fruitfull Isles, where not an Ass can find / A verdent Lust, or Thistle, to his Mind! / How then, must those Poor Silly Asses fare, / That leave their Native Land to Settle there?" The five of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The card satirizes colonial settlement schemes promoted during the 1720 bubble, mocking investors who funded ventures in distant and reputedly inhospitable territories without understanding the real conditions. The verse\'s extended "ass" metaphor—equating foolish investors with stubborn and obstinate animals—is one of the more direct personal insults in the deck.' },

  { row: 64,
    title: 'Insurance on Ships &c. (South Sea Bubble Playing Card, Six of Diamonds)',
    desc: 'A playing card depicting a maritime insurance scheme, showing a dramatic scene at sea with two ships in distress: one crew abandons ship in a rowboat while figures struggle in the water, illustrating the maritime perils the scheme proposed to insure against. The verse reads: "In vain are all Insurances, for Still / The Raging Winds, must answer Heaven\'s Will; / To what Wife purpose do we then Insure, / Since Some must Loose what e\'er the Sea Devour." The six of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse takes a philosophical position against the very concept of insurance, arguing that maritime losses ultimately answer to divine providence rather than human commercial arrangements, while simultaneously satirizing the speculative promotion of insurance companies as investment vehicles. The card\'s imagery of maritime catastrophe visually reinforces the inevitability of loss that the verse asserts.' },

  { row: 65,
    title: 'Rock Salt (South Sea Bubble Playing Card, Seven of Diamonds)',
    desc: 'A playing card depicting a rock salt mining and processing scheme, showing a rugged landscape in which workers hammer at rock formations and extract raw salt while others process the mineral at a barrel-shaped grinder in the center, and a merchant and seated figure examine the finished product in the foreground. The verse reads: "You that are willing to Preserve your Meat, / In Winter Sav\'ry, and in Summer Sweet; / Encourage this Salt Project, and your Coin / Will turn to some Account, at least to Brine." The seven of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. Rock salt extraction was a genuine British industry of commercial importance for food preservation, and the card satirizes its exploitation as a speculative investment opportunity during the 1720 bubble. The verse\'s sardonic promise that investors\' money will turn "at least to Brine" uses the dissolved mineral as a metaphor for the dissolution of invested capital.' },

  { row: 66,
    title: 'Settling Colonies in Accadia, North America (South Sea Bubble Playing Card, Eight of Diamonds)',
    desc: 'A playing card depicting a scheme to establish British colonies in Acadia (present-day Nova Scotia and New Brunswick, Canada), showing a dramatic coastal landing scene in which European settlers in the foreground are attacked by indigenous warriors with bows while dogs run loose and a conflict unfolds across the beach, conveying the dangers of the proposed colonial venture. The verse reads: "He that is Rich, and wants to Fool away, / A Sporting Sum, in North America; / Let him Subscribe himself a Headlong Sharer, / And Asses Ears, Shall Honour him or Bearer." The eight of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. Acadia had been a contested colonial territory between Britain and France since the late seventeenth century, and its settlement remained genuinely dangerous and uncertain, making it a pointed target for the satirist\'s mockery of investors who subscribed to colonial schemes. The verse\'s equation of investors with donkeys sporting "Asses Ears" is among the deck\'s most direct insults.' },

  { row: 67,
    title: 'Pensilvania Company (South Sea Bubble Playing Card, Nine of Diamonds)',
    desc: 'A playing card depicting the Pennsylvania Company scheme, showing an office interior in which investors queue before a counter staffed by Quaker figures—identifiable by their distinctive broad-brimmed hats—while a fool in a pointed dunce cap observes from the corner, satirizing both the promoters and their credulous subscribers. The verse reads: "Come all ye Saints that would for little Buy / Great Tracts of Land, and care not where they lye, / Deal with your Quaking Friends, they\'re Men of Light, / The Spirit hates Deceit and Scorns to Bite." The card satirizes a scheme to sell Pennsylvania land grants by playing on anti-Quaker sentiment, implying that even supposedly honest "Men of Light" were complicit in bubble promotion. The nine of diamonds pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse\'s ironic invocation of the Quaker testimony against deceit—"The Spirit hates Deceit"—is a pointed piece of religious satire suggesting that commercial temptation had corrupted even the most principled communities.' },

  { row: 68,
    title: 'Purchaseing of Estates Illegally Detain\'d (South Sea Bubble Playing Card, Ten of Diamonds)',
    desc: 'A playing card depicting a scheme to purchase estates subject to disputed or illegal title, showing an interior scene in which a solicitor processes documents at a desk while a crowd of claimants waves papers and presses forward from the right, conveying the frenzied demand for the company\'s dubious services. The verse reads: "You that have Dormant Titles to Estates, / Pil\'d on your Closet Shelves to feed the Rats, / Sell them to us, we\'ll gratify your Spite, / And Plague the Rogues that Rob you of your Right." The ten of diamonds pips identify this card\'s position in the South Sea Bubble playing card deck. The scheme exploited dormant legal claims to land and property, appealing to the grievances of dispossessed or cheated landowners who lacked the means to pursue their claims in court. The verse\'s promise to "Plague the Rogues" who had deprived subscribers of their rights illustrates how bubble promoters targeted specific social resentments to attract investment.' },

  { row: 69,
    title: 'Lute-String (South Sea Bubble Playing Card, Ace of Clubs)',
    desc: 'A playing card depicting the Lute-String Company, showing a warehouse or factory scene in which workers carry bolts of fabric while a group conducts what appears to be a forced or contentious transaction outside the building, with the ace of clubs pip in the upper left corner. The verse reads: "These Crafty Managers have play\'d for Years, / The World as Many Tricks as Dancing Bears; / By Bubbling too, they\'ve broke their Ancient Rules, / They first made Lutestrings, but they now make Fools." The Lute-String Company was one of the few bubble-era ventures with a genuine productive history, having manufactured silk lutestring fabric before converting itself into a speculative vehicle during the 1720 frenzy. The verse mocks the company\'s abandonment of legitimate manufacturing in favor of "Bubbling," noting that it now "makes Fools" of its investors rather than fabric. The ace of clubs identifies this card as the start of the clubs suit sequence in the South Sea Bubble playing card deck.' },

  { row: 70,
    title: 'Past-board Manufactory (South Sea Bubble Playing Card, Two of Clubs)',
    desc: 'A playing card depicting a pasteboard (cardboard) manufacturing scheme, showing a workshop interior in which two workers handle large sheets of pasteboard—one rolling or pressing a sheet while another examines the finished product at a worktable. The verse reads: "As Empty Sayings flow from Windy Fools, / So Paistboard Bubbles rise from Paper Skulls; / Madness must Surely be the Towns disease, / When Knaves get Money by Such Whims as these." The two of clubs pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The image of pasteboard manufacture—a material both cheap and hollow—serves as a sustained metaphor for the bubble schemes themselves, which promised solid returns but delivered only worthless paper. The verse\'s equation of speculative promoters with "Windy Fools" and investors with "Paper Skulls" extends the metaphor of hollowness to both parties in the fraudulent exchange.' },

  { row: 71,
    title: 'Trade to Harborough (South Sea Bubble Playing Card, Three of Clubs)',
    desc: 'A playing card depicting a scheme to establish trade through Harborough (likely Market Harborough or a town in Bremen), showing a busy harbor scene with a large sailing ship at anchor, workers unloading cargo, and merchants conducting business on the quayside. The verse reads: "You that delight to take up foreign Linnen, / At Harb\'rough made, a little Town in Bremen, / Encourage Trade abroad for time to come, / And like Kind Fools, neglect your own at home." The card satirizes a scheme to develop foreign trade through a town unsuited to major commerce, possibly confusing an English inland town with its German namesake or mocking a genuinely impractical geographic choice. The three of clubs pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse\'s criticism that investors "neglect your own at home" reflects early eighteenth-century anxieties about the diversion of domestic capital into speculative foreign ventures.' },

  { row: 72,
    title: 'Salt-Petre (South Sea Bubble Playing Card, Clubs)',
    desc: 'A playing card depicting a saltpeter (potassium nitrate) extraction and processing scheme, showing a rural scene in which workers collect and refine saltpeter in the foreground near a cannon—the weapon for which saltpeter was an essential ingredient—while a horseman and a figure carrying a bucket are visible in the background. The verse reads: "Come all ye Black Infernal Powder Makers, / And Rocketeers that deal in Squibs and Crackers, / Buy Petre Stock, Let me be your Adviser, / I will make you [tho\' not Richer] much the Wiser." The clubs suit pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. Saltpeter was a strategically vital material for gunpowder production, giving this scheme a veneer of national security interest that promoters could exploit to attract investors concerned with military readiness. The verse\'s sardonic promise to make investors "much the Wiser" while explicitly declining to make them richer encapsulates the satirist\'s bleak view of the bubble era\'s educational legacy.' },

  { row: 73,
    title: 'Sugar (South Sea Bubble Playing Card, Clubs)',
    desc: 'A playing card depicting a sugar manufacturing or refining scheme, showing a refinery interior in which a bare-chested worker stirs a vat of boiling sugar over a furnace while another worker carries finished sugar loaves to a drying shelf in the background. The verse reads: "Fair Tattling Gossips, you that Love to see, / Fine Sugar blended, with Expensive Tea; / Since you Delight in things, both Dear and Sweet, / Buy Sugar Shares, and you\'ll be Sweetly Bit." The clubs suit pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The card\'s appeal to the fashionable consumption of sweetened tea—a luxury closely associated with elite sociability in early eighteenth-century Britain—illustrates how bubble promoters targeted the leisure habits and consumption patterns of prosperous investors. The verse\'s pun on "Sweetly Bit" (pleasantly deceived, and cheated of one\'s sweetness) is characteristic of the ironic wordplay throughout this satirical card series.' },

  { row: 74,
    title: 'Fatning of Hoggs (South Sea Bubble Playing Card, Clubs)',
    desc: 'A playing card depicting a commercial hog-fattening scheme, showing a farmyard scene with pigs feeding at a trough while a swineherd tends the animals, and—most strikingly—two pig-headed figures with human bodies are seated together in the foreground, representing the foolish investors in the scheme. The verse reads: "Come all ye Bacon making Greasy Rogues, / That want Good Nurses, for your Meagre Hoggs, / Send them to us, and at a Small Expence, / We\'ll fat \'em up, with Offal, Blood, and Grains." The clubs suit pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The card\'s most striking satirical device is the literal depiction of investors as swine—human bodies topped with pig heads—making the equation of speculative foolishness with animal stupidity visually explicit rather than merely metaphorical. The verse\'s promise to fatten investors\' hogs cheaply on offal and blood extends the animal imagery to encompass the entire scheme.' },

  { row: 75,
    title: 'Rose Insurance from Fire (South Sea Bubble Playing Card, Seven of Clubs)',
    desc: 'A playing card satirizing fire insurance as a speculative scheme, showing a street scene in which a building is ablaze on the right while fire brigade workers attempt to battle the flames with hooks and ladders, and a policeman and bystanders observe from the left. The verse reads: "Projecting sure must be a Gainfull Trade, / Since all the Elements are Bubbles made, / They\'re right that gull us with the Dread of Fire, / For fear makes Greater Fools, than Fond Desire." The seven of clubs pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The Rose Insurance Company was one of several fire insurance ventures promoted during the 1720 bubble, competing with the established Sun Fire Office and other earlier insurers. The verse argues that fear—specifically of fire—was an even more effective tool for attracting investors than greed, suggesting that promoters deliberately exploited anxieties about urban fire risk to sell policies and shares.' },

  { row: 76,
    title: 'Buying Seamen\'s Tickets (South Sea Bubble Playing Card, Clubs)',
    desc: 'A playing card depicting a scheme for purchasing sailors\' unpaid wage tickets at a discount, showing a chaotic office interior in which a woman and sailors press toward a desk where officials process transactions, while in the background a man brandishes a stick and another figure appears physically restrained or ejected. The verse reads: "As the Case Stands the Wapping Ale Wives buy, / The Seamen\'s-Tickets for a small Supply; / But t\'is no matter whether Spendthrift Slaves, / Are Chousd\' by Wapping Whores or Bubbling Knaves." The buying of sailors\' pay tickets at heavy discounts was a longstanding form of financial exploitation predating the 1720 bubble, and the card satirizes its conversion into a formal speculative investment scheme. The clubs suit pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The verse\'s reference to "Wapping Whores" and "Bubbling Knaves" places the scheme within the raffish commercial milieu of the Thames waterfront.' },

  { row: 77,
    title: 'Liverpool Fresh-water (South Sea Bubble Playing Card, Clubs)',
    desc: 'A playing card depicting a scheme to supply fresh water to Liverpool and the surrounding western islands, showing a landscape with horse-drawn water carts collecting water from a stream while workers carry buckets, and a church tower rises above the town in the background. The verse reads: "This Town does to our Western Isles deal, / And Serv\'s \'em with Malt Liquors, and with Meal, / Both Excellently Good, then how in Nature, / Can People Brew Fine Drink, and want Fresh Water?" The clubs suit pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The card satirizes a scheme to supply fresh water to Liverpool, contrasting the town\'s reputation for fine malt liquors with its supposed deficiency in clean drinking water. The verse\'s sardonic logic—questioning how a town famous for its brewing could lack fresh water—illustrates the absurdist commercial reasoning that characterized many bubble promotions.' },

  { row: 78,
    title: 'Bleeching of Hair (South Sea Bubble Playing Card, Ten of Clubs)',
    desc: 'A playing card depicting a hair-bleaching and processing scheme, showing a rural workshop in which workers boil hair in a large cauldron over an open fire while another worker holds up bleached hairpieces against a rack from which processed hair hangs to dry in the open air. The verse reads: "Here Dirty Brown, Dark, Red, and Yellow Hair, / Are Bleach\'d, to Colours that are Fine and Fair, / Then Blended so, that half the Whores in Town, / Contribute to adorn one Addle\'d Crown." The ten of clubs pips in the upper left identify this card\'s position in the South Sea Bubble playing card deck. The scheme targeted the fashionable wig trade of early eighteenth-century Britain, proposing to commercially bleach and blend human hair for use in wigs and hairpieces. The mordant verse, connecting the scheme to hair collected from London prostitutes destined to adorn the head of a fool ("Addle\'d Crown"), combines social satire with financial critique in the manner characteristic of this entire card series.' },
];

cards.forEach(({ row, title, desc }) => {
  set(row, 'title', title);
  set(row, 'description', desc);
  Object.entries(bubbleBase).forEach(([k, v]) => set(row, k, v));
});

const newWs = xlsx.utils.aoa_to_sheet(data);
newWs['!cols'] = ws['!cols'];
wb.Sheets['Documents'] = newWs;
xlsx.writeFile(wb, path);
console.log('Done. Updated rows 55-78 (English Bubble Cards, final stretch).');
