const xlsx = require('xlsx');
const path = require('path');

const filePath = path.join(__dirname, '..', 'oov_data_new.xlsx');
const wb = xlsx.readFile(filePath);
const ws = wb.Sheets['Documents'];
const data = xlsx.utils.sheet_to_json(ws, { header: 1 });
const headers = data[0];
const col = {};
headers.forEach((h, i) => { col[h] = i; });

function set(rowIdx, field, value) {
  if (col[field] === undefined) return;
  while (data[rowIdx].length <= col[field]) data[rowIdx].push('');
  data[rowIdx][col[field]] = value;
}
function setDoc(rowIdx, title, description, meta) {
  set(rowIdx, 'title', title);
  set(rowIdx, 'description', description);
  Object.entries(meta).forEach(([k, v]) => set(rowIdx, k, v));
}

setDoc(336, 'Compañía de los Ferro-Carriles de Madrid a Zaragoza y a Alicante (MZA), 500 Franc Share',
  'This engraved stock certificate represents one action of 500 Francs (or 1,900 Reales Vellón) in the Compañía de los Ferro-Carriles de Madrid a Zaragoza y a Alicante, also known as the MZA (Madrid–Zaragoza–Alicante), No. 233055, issued in Madrid on July 1, 1859. The certificate bears the notation "ESTE TITULO SUBSTITUYE AL PRIMITIVO DE IGUAL NUMERO Y FECHA" (This title replaces the original of the same number and date), indicating it was a replacement certificate. The MZA, formed in 1856, was one of Spain\'s two dominant railway companies, connecting Madrid to the Mediterranean coast; together with the Norte railway, it dominated Spanish rail transport until nationalization in 1941.',
  { type: 'Stock Certificate', subjectCountry: 'Spain', issuingCountry: 'Spain', creator: 'Compañía de los Ferro-Carriles de Madrid a Zaragoza y a Alicante', issueDate: '1859-07-01', currency: 'FRF', language: 'Spanish', numberPages: 1, period: '19th Century', notes: 'Compañía MZA, 1 share 500 Francs/1,900 Reales Vellón, No. 233055, Madrid July 1, 1859; replacement certificate' });

setDoc(337, 'Compañía La Petrolífera Nacional, 500 Peseta Share',
  'This engraved stock certificate represents one Series A share of 500 Pesetas in the Compañía La Petrolífera Nacional (National Petroleum Company), No. 17341, issued in San Sebastián on May 15, 1928. The company, with a domicile at Plaza del Centenario 5 in San Sebastián, had a capital of 100,000,000 Pesetas divided into 140,000 Series A shares at 500 Pesetas and 800,000 Series B shares at 50 Pesetas. The certificate features a vignette of an oil derrick over an industrial landscape. The Petrolífera Nacional represents Spain\'s ambitions in petroleum exploration during the 1920s, the decade of international oil company formation following World War I.',
  { type: 'Stock Certificate', subjectCountry: 'Spain', issuingCountry: 'Spain', creator: 'Compañía La Petrolífera Nacional', issueDate: '1928-05-15', currency: 'ESP', language: 'Spanish', numberPages: 1, period: '20th Century', notes: 'Compañía La Petrolífera Nacional, 1 share 500 Pesetas Series A, No. 17341, San Sebastián, May 15, 1928' });

setDoc(338, 'Compañía Petrolera Mexicana "Faros de Aztlán", 50 Shares',
  'This stock certificate represents 50 shares at 50 pesos gold each (total 2,500 pesos) in the Compañía Petrolera Mexicana "Faros de Aztlán", S.A., Certificate No. 0245 (Nos. 012201–012250), Capital 250,000 pesos gold, duration 50 years, domicile Ciudad de México. Issued Mexico City, October 1, 1916. The certificate is decorated with a prominent Aztec warrior figure. "Faros de Aztlán" (Lighthouses of Aztlán) invokes the mythical Aztec homeland, reflecting nationalist aesthetics during the Mexican Revolution. The company was constituted before Notary Don Francisco Merino Ortiz on June 24, 1916, during the revolutionary turbulence of the Carranza presidency.',
  { type: 'Stock Certificate', subjectCountry: 'Mexico', issuingCountry: 'Mexico', creator: 'Compañía Petrolera Mexicana "Faros de Aztlán"', issueDate: '1916-10-01', currency: 'MXN', language: 'Spanish', numberPages: 1, period: '20th Century', notes: 'Compañía Petrolera Mexicana "Faros de Aztlán", 50 shares at 50 pesos gold, No. 0245, Mexico City, October 1, 1916' });

setDoc(339, 'Compañía de las Hulleras de Ujo-Mieres, Five-Share Certificate',
  'This bilingual (Spanish/French) stock certificate represents five shares (Nos. 370241–370245) at 25 Pesetas Oro each (completamente liberadas / entièrement libérées) in the Compañía de las Hulleras de Ujo-Mieres, Concesiones Reunidas de Ujo-Mieres y Riosa, No. 72049. The company, with a capital of 15,000,000 Pesetas Oro, was constituted on November 3, 1893, before Notary Don José Moreno de la Cruz, based in Madrid. The Ujo-Mieres mines operated in the Asturian coalfields of northern Spain—the most important coal mining region in the country—which fueled Spanish industrialization and were the scene of the 1934 Asturian miners\' uprising.',
  { type: 'Stock Certificate', subjectCountry: 'Spain', issuingCountry: 'Spain', creator: 'Compañía de las Hulleras de Ujo-Mieres', issueDate: '1895-01-01', currency: 'ESP', language: 'Spanish', numberPages: 1, period: '19th Century', notes: 'Compañía de las Hulleras de Ujo-Mieres, 5 shares 25 Pesetas Oro each (Nos. 370241-370245), No. 72049, Capital 15,000,000 Pesetas Oro, Madrid' });

setDoc(340, 'Confederate States of America, $1,000 Cotton Loan Bond (1863)',
  'This bond certificate represents a $1,000 bond of the Confederate States of America, Loan Authorized by Act of Congress Approved April 30, 1863 (the Cotton Loan). On the first day of June 1865 (or later date), the Confederate States promised to pay the bearer One Thousand Dollars at the seat of Government. Signed by C.G. Memminger, Secretary of the Treasury of the Confederacy. With attached cotton coupon strips labeled "C.S. Cotton Coupon Loan April 30, 1863." The 1863 Confederate Cotton Loan was a bond issue backed by cotton pledged as collateral, primarily aimed at European investors, representing the Confederacy\'s attempt to leverage its cotton reserves to secure foreign financing during the Civil War.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Confederate States of America', issueDate: '1863-06-01', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Confederate States of America, $1,000 Cotton Loan Bond, Act of Congress April 30, 1863, C.G. Memminger, Register signed' });

setDoc(341, 'Confederate States of America, $500 Bond, Act of August 19, 1861',
  'This bond certificate represents a $500 bond of the Confederate States of America, authorized by Act of Congress of August 19, 1861. The bond promised payment on July 1, 1869 with interest at 8% per annum, payable semi-annually, backed by an export tax on cotton. Signed by C.G. Memminger, Secretary of the Confederate Treasury. With attached coupon strips at the bottom. This was one of the earliest Confederate bond issues, made during the first months of the Civil War, when the Confederate government was still optimistic about quick recognition by European powers and a short conflict.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Confederate States of America', issueDate: '1861-08-19', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Confederate States of America, $500 Bond, 8% per annum, Act of August 19, 1861, C.G. Memminger, with coupon strips' });

setDoc(342, 'Confederate States of America, $500 Bond, Act of February 20, 1863',
  'This bond certificate represents a $500 bond of the Confederate States of America at 7% per annum, authorized by the Act of Congress of February 20, 1863, dated at Richmond on March 2, 1863. The bond promised payment on July 1, 1868, with semi-annual interest coupons, and contained the unusual provision that the Confederate States could defer payment for up to thirty years at the same interest rate upon surrender of the coupons. Signed by the Register of the Treasury. Issued to fund Confederate Treasury notes in the increasingly desperate final phase of the Civil War, when Southern financial resources were rapidly depleting.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Confederate States of America', issueDate: '1863-03-02', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Confederate States of America, $500 Bond, 7% per annum, Act of February 20, 1863, dated Richmond March 2, 1863' });

setDoc(343, 'Société des Comptoirs d\'Importation & d\'Exportation "Congo-Cameroun", 100 Franc Share',
  'This engraved share certificate represents one action of 100 Francs au Porteur (entièrement libérée) in the Société des Comptoirs d\'Importation & d\'Exportation "Congo-Cameroun", a Société Anonyme with capital of 12,000,000 Francs divided into 120,000 shares of 100 Francs each, No. 073774. The statuts were deposited at the Étude of Notaire Laufer in Paris; siège social in Paris. The company operated trading posts (comptoirs) in French Congo and Cameroon, engaging in the import-export trade typical of French Equatorial African colonial commerce in the early twentieth century.',
  { type: 'Stock Certificate', subjectCountry: 'Cameroon', issuingCountry: 'France', creator: 'Société des Comptoirs d\'Importation & d\'Exportation "Congo-Cameroun"', issueDate: '1920-01-01', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Société des Comptoirs d\'Importation & d\'Exportation "Congo-Cameroun", 100 Franc action No. 073774, Capital 12,000,000 Francs, Paris' });

setDoc(344, 'Conseil de la Dette Publique de l\'Ancien Empire Ottoman, Provisional Receipt No. 0,288,837',
  'This provisional receipt (Récépissé Provisoire au Porteur), No. 0,288,837, was issued by the Conseil de la Dette Publique Répartie de l\'Ancien Empire Ottoman in Paris on October 9, 1933. It was delivered in exchange for one named obligation of nominal capital Frs. 500 (or $19.37 or £22) from the Ottoman 5% Emprunt of 1914. Following the dissolution of the Ottoman Empire, the 1923 Treaty of Lausanne allocated portions of the Ottoman public debt among successor states (Turkey, Greece, Bulgaria, and others). The Conseil de la Dette managed this redistribution; these provisional receipts replaced the original Ottoman bonds with new instruments recognizing the holders\' claims. With coupon sheet (coupons 1–10) attached.',
  { type: 'Bond', subjectCountry: 'Turkey', issuingCountry: 'Turkey', creator: 'Conseil de la Dette Publique Répartie de l\'Ancien Empire Ottoman', issueDate: '1933-10-09', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Conseil de la Dette Publique de l\'Ancien Empire Ottoman, Provisional Receipt No. 0,288,837, Ottoman 5% Emprunt of 1914, Paris October 9, 1933, with coupons 1-10' });

setDoc(345, 'State of South Carolina, Six Per Cent Consolidation Bond, $500',
  'This bond certificate represents a $500 Six Per Cent Consolidation Bond of the State of South Carolina, No. DP 1602, secured by an annual tax, with interest payable each January and July in New York and Columbia, S.C., and principal due July 1876. South Carolina\'s Reconstruction-era government issued Consolidation Bonds to restructure the state\'s debt accumulated during the Republican Reconstruction administration. After the Democratic "Redeemer" government regained power in 1876, South Carolina repudiated substantial portions of its Reconstruction debt, making such bonds a flashpoint in the political and financial controversies of the post-Civil War South.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'State of South Carolina', issueDate: '1872-01-01', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'State of South Carolina, Six Per Cent Consolidation Bond, $500, No. DP 1602, secured by annual tax, principal due July 1876' });

setDoc(346, 'Continental Investment Co., Stock Certificate',
  'This stock certificate represents 100 shares of Common Stock in Continental Investment Co., incorporated under the laws of the State of Delaware, Certificate c 53, issued to John V. Lorimer on January 13, 1925. Wells Fargo Bank & Union Trust Co. served as transfer agent and registrar. Signed by M.C. Lewis (Secretary) and John Lorimer. Continental Investment Co. is a Delaware-chartered investment holding company—a common structure during the 1920s investment boom that preceded the Great Crash.',
  { type: 'Stock Certificate', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Continental Investment Co.', issueDate: '1925-01-13', currency: 'USD', language: 'English', numberPages: 1, period: '20th Century', notes: 'Continental Investment Co., Delaware, 100 shares, Certificate c 53, John V. Lorimer, January 13, 1925' });

setDoc(347, 'Dutch Coupons for American Land Shares, C.J.M. De Wolf, Antwerp (1795–1796)',
  'This document contains two interest coupons (No. 827) of fifty Gulden each, payable as exchange money (wisselgeld) at the counting-house of C.J.M. De Wolf in Antwerp, in June 1795 and June 1796 respectively. Each coupon is attached to a share (Acte van Aendeel) of one thousand Gulden in lands in America, payable pursuant to Articles 2 and 3 of the original deed. These coupons document Dutch investment in American land companies during the 1790s—a period when Dutch financiers were among the largest foreign investors in the young United States, purchasing vast land tracts through companies like the Holland Land Company.',
  { type: 'Dividend Coupon', subjectCountry: 'United States', issuingCountry: 'Belgium', creator: 'C.J.M. De Wolf', issueDate: '1795-06-01', currency: 'NLG', language: 'Dutch', numberPages: 1, period: '18th Century or before', notes: 'Two Dutch coupons No. 827, 50 Gulden each for f.1000 American land shares, payable at C.J.M. De Wolf, Antwerp, June 1795 and June 1796' });

setDoc(348, 'Crédit Foncier Agricole du Maroc, 100 Franc Share',
  'This engraved share certificate represents one action of 100 Francs au Porteur in the Crédit Foncier Agricole du Maroc (Agricultural Land Credit Bank of Morocco), No. 8497. The company, constituted by deed before Notaire Brocquei in Banque on March 17, 1920, had a capital of 1,000,000 Francs (10,000 shares at 100 Francs), with siège social at 92, Rue de Richelieu, Paris. The certificate is decorated with a Moorish arch and North African landscape with camels and palm trees. The Crédit Foncier Agricole du Maroc provided mortgage and agricultural financing in the French Protectorate of Morocco, established in 1912, supporting French settler agriculture and land development.',
  { type: 'Stock Certificate', subjectCountry: 'Morocco', issuingCountry: 'France', creator: 'Crédit Foncier Agricole du Maroc', issueDate: '1920-03-17', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Crédit Foncier Agricole du Maroc, 100 Franc action No. 8497, Capital 1,000,000 Francs, Paris, constituted March 17, 1920' });

setDoc(349, 'Connecticut Comptroller\'s Office Interest Certificate, 1792',
  'This printed interest certificate, No. 13,729, from the Connecticut Comptroller\'s Office is dated February 23, 1792, and certifies that Solomon Ensign Jr. is entitled to receive Thirteen Shillings and Six Pence (£0.13.6) Lawful Money out of any funds appropriated for the payment of interest on the liquidated Debt of the State of Connecticut. Signed by A. Kingsbury, Comptroller. Printed by Hudson and Goodwin, Hartford. This document reflects the post-Revolutionary process of settling state war debts, part of the larger debt consolidation that Alexander Hamilton\'s funding program sought to address at the federal level.',
  { type: 'Receipt', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'State of Connecticut, Comptroller\'s Office', issueDate: '1792-02-23', currency: 'USD', language: 'English', numberPages: 1, period: '18th Century or before', notes: 'Connecticut Comptroller\'s Office, Interest Certificate No. 13,729, £0.13.6 for Solomon Ensign Jr., February 23, 1792; printed by Hudson and Goodwin, Hartford' });

setDoc(350, 'The Cuba Company, Common Stock Specimen Certificate',
  'This is a specimen (unissued) Common Stock certificate of The Cuba Company, incorporated under the laws of the State of New Jersey, stamped "SPECIMEN" in red at the bottom corners. The certificate shows agricultural and harvest vignette imagery at the top. The Cuba Company was organized in 1900 by William Van Horne and associates to build the Cuba Railroad, a 350-mile line connecting Santiago de Cuba to the western provinces, which opened up eastern Cuba\'s vast undeveloped territory to sugar cultivation. As a specimen, this certificate was retained by the printer or company as a reference copy.',
  { type: 'Stock Certificate', subjectCountry: 'Cuba', issuingCountry: 'United States', creator: 'The Cuba Company', issueDate: '1910-01-01', currency: 'USD', language: 'English', numberPages: 1, period: '20th Century', notes: 'The Cuba Company, common stock specimen certificate, State of New Jersey; company built the Cuba Railroad ca. 1900' });

setDoc(351, 'Dale Land & Cattle Co., Stock Certificate',
  'This engraved stock certificate represents fifty shares (Certificate No. 8) in the Dale Land & Cattle Co., incorporated under the laws of the State of Texas, Capital Stock $300,000 (3,000 shares at $100 each), issued to J.B. Dale Sr. on March 20, 1895. Places of business: Bonham and Henrietta, Texas; Headquarters: Clay County, Texas. Signed by B.A. McKinney (Secretary) and J.B. Dale (President). The Dale Land & Cattle Co. represented the transition of Texas\'s cattle ranching economy in the post-frontier era, as large operators like the Dale family shifted from open-range ranching to organized land and livestock companies operating in the Cross Timbers and Red River prairies.',
  { type: 'Stock Certificate', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Dale Land & Cattle Co.', issueDate: '1895-03-20', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Dale Land & Cattle Co., 50 shares $100 each, No. 8, J.B. Dale Sr., Bonham & Henrietta/Clay County Texas, March 20, 1895' });

setDoc(352, 'Danforth, Scudder & Co., Business Receipt',
  'This decorative business receipt from Danforth, Scudder & Co. of Boston, dated July 8, 1872, acknowledges receipt of $207.84 from D.T. Saunders on account, per hands Bradford & Anthony, signed per S.R. Mathews. The receipt is printed on a form featuring engravings of a stag and a sheep—possibly indicating a firm involved in livestock trade. Printed by Leonard, Millder & Co., Stationers and Engravers, Congress Street, Boston. Such Victorian-era commercial receipts, printed on elaborately decorated forms to serve simultaneously as receipts and business advertisements, are artifacts of nineteenth-century commercial culture.',
  { type: 'Receipt', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Danforth, Scudder & Co.', issueDate: '1872-07-08', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Danforth, Scudder & Co. (Boston), receipt $207.84, D.T. Saunders, July 8, 1872; printed by Leonard, Millder & Co.' });

setDoc(353, 'Ostend Company (Generale Keijserlijcke Indische Compagnie), Share Subscription Receipt',
  'This manuscript document bears the seal of the Generale Keijserlijcke Indische Compagnie (General Imperial East India Company / Ostend Company) and orders cashier Jan Baptist Cogels Jr. to receive from Anna Rosalia de Bruijn van Holst the sum of 250 Gulden exchange money (wisselgeld) as the first installment payment (25%) on one share of 1,000 Gulden in the capital of the said Company, per the conditions stated in the Company\'s charter (Octroy). Antwerp, August 16, 1723. The Ostend Company was chartered by Habsburg Emperor Charles VI in 1722 to compete in the East India and China trade from the Austrian Netherlands; it was suspended in 1727 under diplomatic pressure from Britain and the Dutch Republic, who viewed it as a threat to their trading monopolies.',
  { type: 'Receipt', subjectCountry: 'Belgium', issuingCountry: 'Belgium', creator: 'Generale Keijserlijcke Indische Compagnie (Ostend Company)', issueDate: '1723-08-16', currency: 'NLG', language: 'Dutch', numberPages: 1, period: '18th Century or before', notes: 'Ostend Company (Generale Keijserlijcke Indische Compagnie) share subscription receipt, 250 Gulden first installment (25% of 1,000 Gulden share), Anna Rosalia de Bruijn van Holst, Antwerp August 16, 1723' });

setDoc(354, 'Grand Society of Russian Railways (Главное Общество Российских Железных Дорог), 125 Ruble Silver Bond',
  'This bond certificate represents one obligation of 125 Silver Metallic Rubles (equivalent to 500 Francs, 20 British Pounds, 402 German Marks, or 238 Dutch Gulden) at 3% from the Third Issue of the Grand Society of Russian Railways (Главное Общество Россiйскихъ Желѣзныхъ Дорогъ), No. 220757. The Grand Society, chartered in 1857, was the principal contractor for building Russia\'s main trunk railway network. Its bonds were placed across European markets; the multi-currency equivalency on the certificate reflects systematic marketing to French, British, German, and Dutch investors. The Third Issue totaled 105,176 bonds for 13,147,000 rubles, issued circa November 3, 1861.',
  { type: 'Bond', subjectCountry: 'Russia', issuingCountry: 'Russia', creator: 'Grand Society of Russian Railways (Главное Общество Российских Железных Дорог)', issueDate: '1861-11-03', currency: 'RUB', language: 'Russian', numberPages: 1, period: '19th Century', notes: 'Grand Society of Russian Railways, Third Issue, 125 Ruble Silver Bond No. 220757, 3%, = 500 Francs = £20 = 402 German Marks = 238 Dutch Gulden' });

setDoc(355, 'N.V. De Woning Maatschappij (Housing Company), Dividend Talon',
  'This document is a dividend talon for share No. 1499 of the Naamlooze Vennootschap De Woning Maatschappij (Housing Company), established in Djakarta (Batavia / Jakarta), Dutch East Indies (now Indonesia). The talon—a stub used to obtain a new coupon sheet when the current one was exhausted—is accompanied by dividend coupons Nos. 46–56 for the share. The De Woning Maatschappij provided housing in the Dutch colonial capital; the high coupon numbers indicate a company that had been paying dividends for many years, with the talon issued when earlier coupon sheets had been fully utilized.',
  { type: 'Dividend Coupon', subjectCountry: 'Indonesia', issuingCountry: 'Netherlands', creator: 'N.V. De Woning Maatschappij', issueDate: '1940-01-01', currency: 'NLG', language: 'Dutch', numberPages: 1, period: '20th Century', notes: 'N.V. De Woning Maatschappij, established in Djakarta (Dutch East Indies), dividend talon for share No. 1499, with coupons 46-56' });

setDoc(356, 'Debito Pubblico del Regno d\'Italia (Italian Public Debt), 5% Rendita Certificate',
  'This certificate from the Gran Libro del Debito Pubblico del Regno d\'Italia (Grand Book of the Public Debt of the Kingdom of Italy) represents a 5% Rendita (perpetual government annuity) with an annual income of 20 lire, No. [001,300], issued from Florence, the provisional capital of the Kingdom of Italy before 1871. The certificate bears a portrait vignette of King Victor Emmanuel II and multiple cancellation and transfer stamps. The Italian 5% Rendita was the primary consolidated sovereign debt instrument of the young Kingdom of Italy (unified 1861), modeled on French and British perpetual government debt instruments.',
  { type: 'Bond', subjectCountry: 'Italy', issuingCountry: 'Italy', creator: 'Kingdom of Italy, Ministry of Finance', issueDate: '1865-01-01', currency: 'ITL', language: 'Italian', numberPages: 1, period: '19th Century', notes: 'Debito Pubblico del Regno d\'Italia, 5% Rendita, annual income 20 lire, issued from Florence; portrait of Victor Emmanuel II' });

setDoc(357, 'Deli-Spoorweg-Maatschappij (Deli Railway Company), 1,000 Gulden Share',
  'This share certificate, No. 7390, represents one share of 1,000 Gulden in the Naamlooze Vennootschap Deli-Spoorweg-Maatschappij (Deli Railway Company), Capital 10,000,000 Gulden, established by deed of June 28, 1888, last amended by Royal Decree of September 5, 1913. Amsterdam, May 5, 1914. Signed by the Commission-Chairman and Director. The Deli Railway Company operated a railway network in the Deli region of East Sumatra (Dutch East Indies, now Indonesia), serving the legendary Deli tobacco and rubber plantations whose products—particularly the thin-leafed Deli tobacco used as cigar wrappers—commanded premium prices in European and American markets.',
  { type: 'Stock Certificate', subjectCountry: 'Indonesia', issuingCountry: 'Netherlands', creator: 'Deli-Spoorweg-Maatschappij', issueDate: '1914-05-05', currency: 'NLG', language: 'Dutch', numberPages: 1, period: '20th Century', notes: 'Deli-Spoorweg-Maatschappij (Deli Railway Company, Sumatra), 1,000 Gulden share No. 7390, Capital 10,000,000 Gulden, Amsterdam, May 5, 1914' });

setDoc(358, 'Société Belge d\'Exportation (Jules Van der Laat & Cie), Action de Fondation',
  'This founders\' share (Action de Fondation No. 021, Coupure No. 08) represents 1/10 of a Founder\'s Share of the Société Belge d\'Exportation, a commandite par actions (limited partnership by shares) with raison sociale Jules Van der Laat & Cie, Capital Social 5,000,000 Francs (10,000 shares at 500 francs each). Constituted by authentic act on July 29, 1901, for thirty years. Siège Social: Anvers (Antwerp). Gérant: Jules Van der Laat; two Commissaires. Actions de Fondation—founders\' shares without fixed par value, entitling holders to a portion of surplus profits—were a distinctive feature of Belgian and French corporate law that rewarded those who organized or contributed non-monetary assets to a company.',
  { type: 'Founders Share', subjectCountry: 'Belgium', issuingCountry: 'Belgium', creator: 'Société Belge d\'Exportation, Jules Van der Laat & Cie', issueDate: '1901-07-29', currency: 'BEF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Société Belge d\'Exportation (Jules Van der Laat & Cie), Action de Fondation No. 021, Coupure 08, représentant 1/10 de l\'Action de fondation, Antwerp, July 29, 1901' });

setDoc(359, 'Banque Royale (John Law), 10 Livres Tournois Banknote, 1720',
  'This printed banknote reads: "LA BANQUE promet payer au Porteur à vüe Dix livres Tournois en Especes d\'Argent, valeur reçeüe. A Paris le premier Juillet mil sept cens vingt." No. 495,360. Labeled "Division." Witnessed by Fenelon/Giraudeau, signed by Bourgeois/Delanauze, and controlled by Durevest/Granet. John Law\'s Banque Royale (previously the Banque Générale, established 1716) issued paper notes convertible to silver, underpinning the Mississippi Company stock bubble. This note, dated July 1, 1720, was issued as the bubble was catastrophically collapsing—the bank suspended silver payments in May 1720, and was liquidated before year\'s end. It is a primary artifact of one of history\'s most famous financial crises and the first large-scale paper money experiment in Europe.',
  { type: 'Banknote', subjectCountry: 'France', issuingCountry: 'France', creator: 'Banque Royale', issueDate: '1720-07-01', currency: 'FRF', language: 'French', numberPages: 1, period: '18th Century or before', notes: 'Banque Royale (John Law), 10 livres Tournois "Division" banknote No. 495,360, Paris July 1, 1720; issued during collapse of Mississippi bubble' });

setDoc(360, 'Compagnie Française du Haut & du Bas Congo, 5,000 Franc Ordinary Share',
  'This ornately engraved share certificate represents one Ordinary Share (Action Ordinaire) of 5,000 Francs au Porteur, entièrement libérée, No. 068,570, in the Compagnie Française du Haut & du Bas Congo, a Société Anonyme Agricole Industrielle et Commerciale de l\'Afrique Équatoriale. Capital Social: 850,000,000 Francs divided into 170,000 shares (34,000 priority shares + 136,000 ordinary shares at 5,000 Francs each). Statuts deposited at the Étude of Notaire Aubrion, Paris. Signed by J. Cousin (Président-Directeur Général). The certificate is decorated with elephant heads and scenes of the Congo basin. The company was one of the major concessionary companies operating in French Equatorial Africa.',
  { type: 'Stock Certificate', subjectCountry: 'Republic of the Congo', issuingCountry: 'France', creator: 'Compagnie Française du Haut & du Bas Congo', issueDate: '1920-01-01', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Compagnie Française du Haut & du Bas Congo, 5,000 Franc Ordinary Share No. 068,570, Capital 850,000,000 Francs, Paris' });

setDoc(361, 'Banco Giro di Venezia (Venice Giro Bank), 100 Ducat Cedula',
  'This document is a printed cedula (banknote) of the Banco Giro di Venezia (Venice Giro Bank / Bank of Transfer), stating it is to be received as effective money by all Royal and Public Cash Offices in payment of customs, land, and all other contributions, and by the Giro Bank\'s own cashier for exchange in account (in partita). Issued pursuant to the proclamation of October 1, 1798. Per Ducati Cento (100 Ducats) = £8. No. 1175. Signed by Giovannelli and Schiantavello. The Banco del Giro, founded in Venice in 1619, was one of Europe\'s earliest public giro banks; this note was issued in 1798 under Austrian Habsburg administration of Venice following Napoleon\'s 1797 conquest.',
  { type: 'Banknote', subjectCountry: 'Italy', issuingCountry: 'Italy', creator: 'Banco Giro di Venezia', issueDate: '1798-10-01', currency: 'VEN', language: 'Italian', numberPages: 1, period: '18th Century or before', notes: 'Banco Giro di Venezia, 100 Ducat cedula No. 1175, issued per proclamation of October 1, 1798 under Austrian administration; signed by Giovannelli and Schiantavello' });

setDoc(362, 'Overend, Gurney and Company Limited, £50 Share',
  'This share certificate, No. 72249, certifies that John Metcalfe Smith, Esq., of Leeds, is the registered proprietor of one share of £50 (with £15 paid up) in the Capital Stock of Overend, Gurney and Company Limited, registered and incorporated on July 12, 1865, under the Companies Act 1862. Secretary: Wm. Bos. November 15, 1865. Overend, Gurney & Company—known as "the bankers\' bank" and the largest discount house in London—converted to a limited liability company in 1865 to raise fresh capital. On May 10, 1866, the company suspended payments, triggering "Black Friday"—the worst financial panic in British history since 1825—and leading to thousands of investor losses across the country.',
  { type: 'Stock Certificate', subjectCountry: 'United Kingdom', issuingCountry: 'United Kingdom', creator: 'Overend, Gurney and Company Limited', issueDate: '1865-11-15', currency: 'GBP', language: 'English', numberPages: 1, period: '19th Century', notes: 'Overend, Gurney and Company Limited, £50 share No. 72249 (£15 paid), John Metcalfe Smith, Leeds, November 15, 1865; company failed May 1866 causing "Black Friday"' });

setDoc(363, 'Eagle Bank of New-Haven, Stock Transfer Receipt',
  'This printed certificate from the Eagle Bank of New-Haven records that W.A. Brockett [?] has one share of $100 in the Capital Stock of the Eagle Bank of New-Haven standing to his credit on the books of the bank, this day transferred. Dated August 10, 1824. Signed by the Cashier. "N.B.—Transfers of Stock must be made at the Bank in Person or by Attorney." The Eagle Bank was a Connecticut state-chartered commercial bank established in the early republic, one of the many small state banks that proliferated across New England following the War of 1812.',
  { type: 'Stock Certificate', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Eagle Bank of New-Haven', issueDate: '1824-08-10', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Eagle Bank of New-Haven, 1 share $100, W.A. Brockett, August 10, 1824; Connecticut state-chartered bank' });

setDoc(364, 'Éclairage Électrique de St. Pétersbourg, 250 Franc Preference Share',
  'This engraved share certificate represents one Preference Share (Action Privilégiée) of 250 Francs, entièrement libérée, No. 38859, in the Société Anonyme de l\'Éclairage Électrique de St. Pétersbourg (Electric Lighting of St. Petersburg), constituted by notarial deed in Brussels and published in the Moniteur Belge of June 11, 1891, No. 1288. Siège Social: Bruxelles. Capital: 10,000,000 Francs (40,000 preference shares at 250 Francs + 20,000 ordinary shares). The certificate features an Art Nouveau electric lamp arch and a panoramic view of the St. Petersburg waterfront, illustrating how Belgian capital and engineering financed urban electrification in the Russian Empire.',
  { type: 'Stock Certificate', subjectCountry: 'Russia', issuingCountry: 'Belgium', creator: 'Société Anonyme de l\'Éclairage Électrique de St. Pétersbourg', issueDate: '1891-06-11', currency: 'BEF', language: 'French', numberPages: 1, period: '19th Century', notes: 'Éclairage Électrique de St. Pétersbourg, 250 Franc preference share No. 38859, Belgian company providing electric lighting in St. Petersburg, constituted Brussels 1891' });

setDoc(365, 'Magyar Jelzálog-Hitelbank (Hungarian Mortgage Credit Bank), 100 Florin Prize Bond',
  'This trilingual (Hungarian/French/German) bond certificate represents a 4½% Nyeremény-Kötvény / Obligation à Primes / Prämien-Obligation (Prize Bond) of one hundred Florins (Egyszáz forintról / Cent Florins / Hundert Gulden) in the Magyar Jelzálog-Hitelbank (Société de Crédit Hypothécaire du Royaume de Hongrie / Ungarische Hypotheken-Bank), Series 2884, No. 061, Budapest, July 1, 1880. The Hungarian Mortgage Credit Bank, established in 1870, was Hungary\'s principal institution for long-term mortgage financing. Prize bonds (nyeremény-kötvények) were widely popular in Central Europe, combining regular interest payments with periodic lottery-style prize drawings.',
  { type: 'Bond', subjectCountry: 'Hungary', issuingCountry: 'Hungary', creator: 'Magyar Jelzálog-Hitelbank', issueDate: '1880-07-01', currency: 'HUF', language: 'Hungarian', numberPages: 1, period: '19th Century', notes: 'Magyar Jelzálog-Hitelbank, 4½% 100 Florin Prize Bond, Series 2884, No. 061, Budapest July 1, 1880; trilingual Hungarian/French/German' });

setDoc(366, 'El Callao Consolidated Gold Mining Company Limited, Share Warrant for Five Shares',
  'This share warrant, Warrant No. 020887, certifies the bearer\'s ownership of five shares (Nos. 213621–213625) in the El Callao Consolidated Gold Mining Company Limited, Capital £800,000 (800,000 shares of £1 each). London, August 22, 1903. El Callao, in the Bolívar state of Venezuela, was one of the world\'s richest gold mining districts in the late nineteenth century; its mines, discovered around 1871, produced remarkable yields and attracted major British investment. The company was organized to consolidate mining operations in the district and continued operating through the early twentieth century.',
  { type: 'Share Warrant', subjectCountry: 'Venezuela', issuingCountry: 'United Kingdom', creator: 'El Callao Consolidated Gold Mining Company Limited', issueDate: '1903-08-22', currency: 'GBP', language: 'English', numberPages: 1, period: '20th Century', notes: 'El Callao Consolidated Gold Mining Company Limited, Share Warrant No. 020887, 5 shares (213621-213625), Capital £800,000, London, August 22, 1903' });

setDoc(367, 'Société Anonyme d\'Exploitation de Phu-Quoc, 100 Franc Share',
  'This elegantly designed share certificate represents one action of 100 Francs au Porteur, entièrement libérée, No. 032,638, in the Société Anonyme d\'Exploitation de Phu-Quoc, with siège social at 55, Rue Lafayette, Paris. Statuts received before Notaire Nobert Dupont, Paris. The certificate features a striking design: a map silhouette of Phu Quoc island at center, flanked by a tropical panorama with sea views and dense vegetation. Phu Quoc is a large island in the Gulf of Thailand, then part of French Cochinchina (now southern Vietnam), known for pepper cultivation and fish sauce production. The company exploited the island\'s agricultural and natural resources as a concession under French colonial authority.',
  { type: 'Stock Certificate', subjectCountry: 'Vietnam', issuingCountry: 'France', creator: 'Société Anonyme d\'Exploitation de Phu-Quoc', issueDate: '1910-01-01', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Société Anonyme d\'Exploitation de Phu-Quoc, 100 Franc action No. 032,638, Paris, 55 Rue Lafayette; features map of Phu Quoc island' });

setDoc(368, 'Ferro-Carril y Almacenes de Depósito de Santiago de Cuba, $100 Share',
  'This engraved stock certificate, No. 7272, is a Cédula de Propiedad (property title) for one share of $100 in the Ferro-Carril y Almacenes de Depósito de Santiago de Cuba (Railroad and Warehouses of Santiago de Cuba), issued to Gabriel de Llamas. Santiago de Cuba, April 20, 1861. Signed by J.M. de Llaguno (President), Lino [?] (Contador), and J.S. Lozano (Secretary). The company combined railway operations with storage warehouses (almacenes de depósito), a common structure in colonial Cuban enterprise that served the export economy for sugar, coffee, and other agricultural products shipped through Santiago de Cuba, the island\'s second city.',
  { type: 'Stock Certificate', subjectCountry: 'Cuba', issuingCountry: 'Cuba', creator: 'Ferro-Carril y Almacenes de Depósito de Santiago de Cuba', issueDate: '1861-04-20', currency: 'CUP', language: 'Spanish', numberPages: 1, period: '19th Century', notes: 'Ferro-Carril y Almacenes de Depósito de Santiago de Cuba, 1 share $100, No. 7272, Gabriel de Llamas, Santiago de Cuba, April 20, 1861' });

setDoc(369, 'Commonwealth of Pennsylvania, Five Per Cent Stock of 1825, $100',
  'This printed bond certificate, No. 71, certifies that there is due from the Commonwealth of Pennsylvania unto James P. Parker in trust of Philadelphia, or his assigns, the sum of one hundred dollars bearing interest at five per centum per annum from August 1, 1829, payable semi-annually at the Bank of Pennsylvania, being stock created pursuant to an Act of Assembly of April 11, 1825, "An act authorizing a loan"—principal reimbursable fifteen years after January 1, 1825. Treasury Department of Pennsylvania, November 18, 1829. Countersigned by State Treasurer Mahon and Auditor General David Mason. Printed by Mowry & Amnon, Harrisburg. Pennsylvania issued bonds like this to finance canal improvements, including the Pennsylvania Main Line of Public Works.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Commonwealth of Pennsylvania', issueDate: '1829-11-18', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Commonwealth of Pennsylvania, Five Per Cent Stock of 1825, $100, No. 71, James P. Parker in trust, November 18, 1829; printed by Mowry & Amnon, Harrisburg' });

setDoc(370, 'Fosses à Charbon de M. le Marquis de Traisnel, Interest Share',
  'This manuscript share document, No. 263, from the Compagnie des Fosses à Charbon de M. le Marquis de Traisnel (Company of the Coal Mines of the Marquis de Traisnel), is signed by Directors La Marsche and Dehault and dated June 13, 1781. It certifies that the holder is the proprietor of one "intérêt" (interest/participation share) in the enterprise of the said coal mines, and will participate proportionally in the profits and losses of the Company, subject to assessments for loans (emprunts) and contributions already made or to be made. Transfer requires Company approval. The company operated in the Aniéni region of France, representing an early form of corporate share in a French pre-revolutionary coal mining enterprise.',
  { type: 'Interest Share', subjectCountry: 'France', issuingCountry: 'France', creator: 'Compagnie des Fosses à Charbon de M. le Marquis de Traisnel', issueDate: '1781-06-13', currency: 'FRF', language: 'French', numberPages: 1, period: '18th Century or before', notes: 'Fosses à Charbon de M. le Marquis de Traisnel, Interest Share No. 263, signed by La Marsche and Dehault, June 13, 1781; pre-revolutionary French coal mining share' });

setDoc(371, 'Fukuyama-Han (Bingo Province) Silver Note, 1 Mon-me (1730)',
  'This narrow printed paper currency note is a silver note (銀札 / ginsatsu) issued by the Fukuyama-Han (Fukuyama Domain) in Bingo Province (now part of Hiroshima Prefecture, Japan), denominated in 1 Mon-me (一匁), dated 1730. The note displays a deity figure (likely Ebisu, god of fortune and commerce) and is printed in the characteristic vertical format of Japanese Edo-period domain currency. Domain currencies (hansatsu) were paper money issued by individual feudal lords (daimyo) throughout the Edo period (1603–1868), circulating only within the issuing domain. The Fukuyama Domain was a prominent coastal fief on the Seto Inland Sea.',
  { type: 'Banknote', subjectCountry: 'Japan', issuingCountry: 'Japan', creator: 'Fukuyama-Han (Fukuyama Domain)', issueDate: '1730-01-01', currency: 'JPY', language: 'Japanese', numberPages: 1, period: '18th Century or before', notes: 'Fukuyama-Han (Bingo Province) silver note (銀札), 1 Mon-me denomination, 1730; Japanese Edo-period feudal domain currency (hansatsu)' });

setDoc(372, 'General Investment Corporation, Stock Purchase Warrant',
  'This stock purchase warrant (No. NCW5418) of the General Investment Corporation, incorporated under the laws of the State of Delaware, certifies that the bearer is entitled to purchase, at any time on or before September 14, 1928 (or a later date), fully paid and non-assessable shares of Common Stock of General Investment Corporation at $8 per share. Signed by Boston, Massachusetts. Issued June 13, 1938 (date visible on certificate). Stock purchase warrants were issued as sweeteners attached to bond offerings or as stand-alone instruments, giving holders the right—but not the obligation—to buy shares at a fixed price, functioning as early financial options.',
  { type: 'Stock Warrant', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'General Investment Corporation', issueDate: '1938-06-13', currency: 'USD', language: 'English', numberPages: 1, period: '20th Century', notes: 'General Investment Corporation (Delaware), Stock Purchase Warrant No. NCW5418 to purchase common stock, Boston, June 13, 1938' });

setDoc(373, 'Gouvernement Impérial du Japon, 4½% Loan of 1910, 500 Franc Bond',
  'This green-printed bond certificate represents a 500 Franc bond from the 4½% Imperial Japanese Government Loan of 1910 (Emprunt de Quatre Cent Cinquante Millions de Francs / 450,000,000 Franc Loan), Series 30, No. 403578. Dated May 15, 1911. The certificate bears a vignette of Mount Fuji. Japanese government bonds were extensively placed in European capital markets—particularly Paris and London—in the early twentieth century to finance Japanese industrialization and military expenditure following the victories in the Sino-Japanese (1894–95) and Russo-Japanese (1904–05) Wars. France was a major holder of Japanese sovereign debt in this period.',
  { type: 'Bond', subjectCountry: 'Japan', issuingCountry: 'Japan', creator: 'Gouvernement Impérial du Japon', issueDate: '1911-05-15', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Gouvernement Impérial du Japon, 4½% Emprunt de 1910 (450 Million Francs), 500 Franc bond, Series 30, No. 403578, May 15, 1911; Mount Fuji vignette' });

setDoc(374, 'Gouvernement de la Nouvelle-Calédonie et Dépendances, 4% Loan of 1931, 1,000 Franc Bond',
  'This bond certificate represents a 4% obligation of 1,000 Francs au Porteur, No. 008,679, from the Gouvernement de la Nouvelle-Calédonie et Dépendances (Government of New Caledonia and Dependencies), Emprunt 4% 1931, Net d\'Impôts Présents et Futurs. Total issue: 34,500 bonds of 1,000 Francs each (34,500,000 Francs). Paris, August 31, 1931. With attached coupon sheet. New Caledonia, a French Pacific territory, issued bonds to finance colonial infrastructure at the onset of the Great Depression, when global nickel prices—the territory\'s chief export—had already begun to collapse, foreshadowing the financial strains of the 1930s colonial economies.',
  { type: 'Bond', subjectCountry: 'New Caledonia', issuingCountry: 'France', creator: 'Gouvernement de la Nouvelle-Calédonie et Dépendances', issueDate: '1931-08-31', currency: 'FRF', language: 'French', numberPages: 1, period: '20th Century', notes: 'Gouvernement de la Nouvelle-Calédonie et Dépendances, 4% Emprunt 1931, 1,000 Franc bond No. 008,679, Paris, August 31, 1931; 34,500 total bonds' });

setDoc(375, 'Republic of Texas Government Bond, $100',
  'This bond certificate of the Republic of Texas promises to pay the bearer One Hundred Dollars with interest at eight percent per annum, payable semi-annually from date, redeemable from the Sinking Fund of the Republic at the Treasury at Houston. "Government Bond, payable to holder. Receivable for all Government Duties." Signed by John F. Chalmers (Secretary) and David G. Burnet (or another authorized signatory). With ten semi-annual interest coupon strips at the bottom. The Republic of Texas (1836–1846) issued bonds to finance its government and military operations as an independent republic between its victory at San Jacinto and its annexation by the United States. Texas bonds were a significant form of frontier-era sovereign debt.',
  { type: 'Bond', subjectCountry: 'United States', issuingCountry: 'United States', creator: 'Republic of Texas', issueDate: '1840-01-01', currency: 'USD', language: 'English', numberPages: 1, period: '19th Century', notes: 'Republic of Texas Government Bond, $100, 8% semi-annual interest, signed by John F. Chalmers (Secretary); receivable for all government duties, with coupon strips' });

const newWs = xlsx.utils.aoa_to_sheet(data);
newWs['!cols'] = ws['!cols'];
wb.Sheets['Documents'] = newWs;
xlsx.writeFile(wb, filePath);
console.log('Done. Updated rows 336-375.');
